version: '3.4'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      vpcbr:
        ipv4_address: 10.4.1.0

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:29092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: javainuse-topic:1:1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      vpcbr:
        ipv4_address: 10.4.1.1

  kafka_sender:
    build: KafkaSender/.
    depends_on:
      - kafka
    networks:
      vpcbr:
        ipv4_address: 10.4.0.2
    volumes:
      - ./KafkaSender:/io
  
  kafka_receiver:
    build: KafkaReceiver/.
    depends_on:
      - kafka
    networks:
      vpcbr:
        ipv4_address: 10.4.0.3
    volumes:
      - ./KafkaReceiver:/io

  receiver_to_gdrive:
    build: ReceiverToGDrive/.
    depends_on:
      - kafka
    networks:
      vpcbr:
        ipv4_address: 10.4.0.4
    volumes:
      - ./ReceiverToGDrive:/io


networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.4.0.0/16
          gateway: 10.4.0.1
